In [1]:
from utils import *

# Manipulate data with `ndarray`

By design similar to numpy

We’ll start by introducing the `NDArray`, MXNet’s primary tool for storing and transforming data. If you’ve worked with `NumPy` before, you’ll notice that a NDArray is, by design, similar to NumPy’s multi-dimensional array. 

## Get started

To get started, let's import the `ndarray` package (`nd` is shortform) from MXNet.

In [3]:
from mxnet import nd
import mxnet as mx
import numpy as np




Next, let's see how to create a 2D array (also called a matrix) with values from two sets of numbers: 1, 2, 3 and 4, 5, 6. This might also be referred to as a tuple of a tuple of integers.

NDArray from tuples

In [4]:
nd.array(((1, 2, 3), (5, 6, 7)))


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

We can also create a very simple matrix with the same shape (2 rows by 3 columns) but fill it with 1s.

1s

In [5]:
x = nd.ones(shape=(2, 3))
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

Often we’ll want to create arrays whose values are sampled randomly. 
For example, sampling values uniformly between -1 and 1. Here we create the same shape, but with random sampling.

Randomly sampled

In [6]:
y = nd.random.uniform(low=-1, high=1, shape=(2,3))
y


[[0.09762704 0.18568921 0.43037868]
 [0.6885315  0.20552671 0.71589124]]
<NDArray 2x3 @cpu(0)>

As with NumPy, the dimensions of each NDArray are accessible by accessing the `.shape` attribute. We can also query its `size`, which is equal to the product of the components of the shape. In addition, `.dtype` tells the data type of the stored values. dtype is important, support for float16

NDArray metadata

In [7]:
(x.shape, x.size, x.dtype, x.context)

((2, 3), 6, numpy.float32, cpu(0))

Type

In [18]:
nd.ones((2,3), dtype=np.uint8)


[[1 1 1]
 [1 1 1]]
<NDArray 2x3 @cpu(0)>

Context

In [19]:
nd.ones((2,3), ctx=mx.cpu(0))


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

## Operations

NDArray supports a large number of standard mathematical operations. Such as element-wise multiplication:

In [8]:
x


[[0.09762704 0.18568921 0.43037868]
 [0.6885315  0.20552671 0.71589124]]
<NDArray 2x3 @cpu(0)>

In [ ]:
y

In [20]:
x * y


[[ 0.13608909 -0.21443039  0.8511933 ]
 [ 0.6721575  -0.8579279  -0.32520765]]
<NDArray 2x3 @cpu(0)>

Exponentiation

In [21]:
x.exp()


[[2.7182817 2.7182817 2.7182817]
 [2.7182817 2.7182817 2.7182817]]
<NDArray 2x3 @cpu(0)>

And grab a matrix’s transpose to compute a proper matrix-matrix product:

Matrix multiplication

In [11]:
x.shape, y.shape

((2, 3), (2, 3))

In [12]:
nd.dot(x, y.T)


[[ 0.71369493  1.60994947]
 [ 0.71369493  1.60994947]]
<NDArray 2x2 @cpu(0)>

## Indexing


Read the 2nd and 3d columns

In [13]:
y


[[ 0.09762704  0.18568921  0.43037868]
 [ 0.68853152  0.20552671  0.71589124]]
<NDArray 2x3 @cpu(0)>

In [14]:
y[:, 1:3]


[[ 0.18568921  0.43037868]
 [ 0.20552671  0.71589124]]
<NDArray 2x2 @cpu(0)>

Writing to a specific element

Writing

In [15]:
y[1:2, 0:2] = 4
y


[[ 0.09762704  0.18568921  0.43037868]
 [ 4.          4.          0.71589124]]
<NDArray 2x3 @cpu(0)>

## Converting between MXNet NDArray and NumPy

Converting MXNet NDArrays to and from NumPy is easy. The converted arrays do not share memory.

In [16]:
a = x.asnumpy()
(type(a), a)

(numpy.ndarray, array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=float32))

In [17]:
nd.array(a)


[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>